### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by StefForBSI** [firling/YAMS#2]
Vous avez bien avancé c'est très bien.
Votre grille est un peu complexe. Elle est de type int [13][10] et vous la passez en paramètre int (*gr)[10] ou quelque chose approchant. La bonne méthode pour passer un tableau à deux dimensions en paramètre de fonction est de passer un pointeur, puis un entier pour chacune des dimensions.

`(int [13][10]) -> (int * grille, int i, int j)`

Dans votre cas, je pense qu'il serait plus simple de la passer en global. Cela évite de la recopier (partiellement) à chaque appel.

**Comment by D-XIII** [comment]
Merci du retour, nous avons effectué le changement
